stages:
  - build
  - test

variables:
  GOPATH: /go
  GOLANG_VERSION: "1.25.5"
  GOLINT_VERSION: "v2.7.0"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    command: [ "--tls=false" ]

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${GOPATH}/pkg/mod
    - ${GOPATH}/bin

build:
  stage: build
  image: golang:${GOLANG_VERSION}
  needs: [ ]
  script:
    - go mod tidy
    - go mod download
    - go build -mod=readonly ./...

lint:
  stage: test
  needs: [build]
  image: golangci/golangci-lint:${GOLINT_VERSION}
  script:
    - "! gofmt -l . | grep -q ."
    - golangci-lint run --timeout 5m0s

test:
  stage: test
  image: golang:${GOLANG_VERSION}
  needs: [ build ]
  script:
    - go test ./... -v -coverprofile=coverage.out
    - go tool cover -func=coverage.out
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)%$/'
  artifacts:
    paths:
      - coverage.out